version: '3.3'

# this is a SAMPLE file. Do not use for build or deployments

# use the following to restrict which OS this is built on
# containerOS: alpine

services:
    confluent:
# build arguments, only needed for building
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: confluent
                FROM_BASE: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/openjdk/${JAVA_VERSION:-8.171.11-r0}:${BASE_TAG:-latest}
                CONFLUENT_VERSION: ${CONFLUENT_VERSION:-5.2.1}
                KAFKA_USER_DIR: /usr/local/confluent
                KAFKA_USER_NAME: kafka
                SCALA_DISTRO: ${SCALA_DISTRO:-2.12}
                ZOOKEEPER_VERSION: ${ZOOKEEPER_VERSION:-3.4.13}
            cache_from:
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}thirdparty/${CONTAINER_OS:-alpine}:${OS_VERSION:-3.8}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/openjdk/${JAVA_VERSION:-8.171.11-r0}:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: confluent
                version.cbf: $CBF_VERSION
        container_name: confluent
# common arguments, for building and deploy 
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            JMX_PORT: 7203
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://confluent:9092
            KAFKA_ADVERTISED_HOST_NAME: THIS_HOST
            KAFKA_BROKER_ID: 3
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_PORT: 9092
            KAFKA_NUM_PARTITIONS: 1
            KAFKA_UID: 1000
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            ZOOKEEPER_HOST: zookeeper
            ZOOKEEPER_INIT_LIMIT: 10
            ZOOKEEPER_MY_ID: 3
            ZOOKEEPER_PORT: 2181
            ZOOKEEPER_SYNC_LIMIT: 5
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_TIMEOUT: 6000
        extra_hosts:
            - "zookeeper:THIS_HOST"
        hostname: confluent
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/confluent/${KAFKA_VERSION:-2.0.0}:${CONTAINER_TAG:-latest}
# deploy arguments, not needed for building
        logging:                              # limit size of logs @runtime so that we do not run out of space 
            driver: json-file
            options:
                max-size: "10m"
                max-file: "3"
#        ports:                                #ports exposed 
#            - "2181:2181"
#            - "9092:9092"
        volumes:
            - ./vols/data:/usr/local/confluent/data
# application logs
            - ./vols/logs:/usr/local/confluent/logs
