version: '3.3'

# repo: https://github/ballab1/kafka.git

services:
    confluent:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: confluent
                FROM_BASE: ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/openjdk/${JAVA_VERSION:-17.0.9_p8-r0}:${BASE_TAG:-latest}
                CONFLUENT_VERSION: ${CONFLUENT_VERSION:-7.5.2}
                KAFKA_USER_DIR: /usr/local/confluent
                KAFKA_USER_NAME: kafka
                SCALA_DISTRO: ${SCALA_DISTRO:-2.12}
            cache_from:
                - ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}thirdparty/${CONTAINER_OS:-alpine}:${OS_VERSION:-3.19.0}
                - ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/openjdk/${JAVA_VERSION:-17.0.9_p8-r0}:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: confluent
                container.parent: $CONTAINER_PARENT
                version.cbf: $CBF_VERSION
        container_name: confluent
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        hostname: confluent
        image: ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/confluent/${CONFLUENT_VERSION:-7.5.2}:${CONTAINER_TAG:-latest}
